# Generated by Django 3.0.7 on 2020-06-07 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestExample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='descritption',
            field=models.TextField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='published',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
